@extends($templatePath.'.shop_layout')

@section('main')
  <div class="row terms-condition" style="font-size: 16px; color: rgb(100, 100, 100)">
    <div class="col-xs-10 col-xs-offset-1">
        <p>
            <strong>Terms &amp; Conditions:</strong>
            <br /><strong>Governing law</strong>
            <br /><strong>Privacy Policy</strong>
            <br /><strong>Shipping / Delivery</strong>
            <br /><strong>Refunds</strong>
            <br /><strong>Secure checkout</strong>
            <br /><strong>General</strong>
            <br />
        </p>
        
        <p>Please read our Terms and Conditions before placing your order. By placing your order you agree to be bound by the following Terms and Conditions:</p>
        
        <ol>
            <li>
                <p><strong>Governing law:</strong> This document constitutes a binding agreement the you, the customer (&ldquo;You&rdquo; or &ldquo;Customer&rdquo;), and FlowCell Inc, the owner and administrator of FluidsForLife.com website and all content and functionality contained herein (&ldquo;Our&rdquo;, &ldquo;Us&rdquo;, or &ldquo;Company&rdquo;) (collectively, the &ldquo;Parties&rdquo; or &ldquo;We&rdquo;). These terms and conditions, as well as any additional terms, conditions and covenants referenced in or made available by hyperlink in this document (collectively, these &ldquo;Terms&rdquo;, &ldquo;Terms of Use&rdquo; or this &ldquo;Agreement&rdquo;), govern Your use of and access to this Website and any and all of its sub-pages (collectively, the &ldquo;Website&rdquo;).</p>
                <p>All contracts for the supply of goods (&ldquo;Goods&rdquo;) distributed by ("the Distributor") FluidsForLife to a customer (&ldquo;the Purchaser&rdquo;) will be subject to the following terms and conditions. the Purchaser accepts that these terms and conditions shall apply to any Contract between the parties in preference to the Purchaser&rsquo;s own terms and conditions (if any). Interpretation of these terms and conditions and any contract to which they shall apply shall be governed by USA Law. The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
            </li>
            <li><p><strong>Privacy policy:</strong> Your submission of personal information through the store is governed by our Privacy Policy. You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks.</p></li>
            <li><p><strong>Shipping policy:</strong> The orders will be shipped from manufacturer to the Purchaser, as soon as possible, but subject to availability. by FluidsForLife (FFL) makes every effort to ensure all orders are shipped within seven days after being placed. If the shipping is delayed by manufacturer due to low stocks, the Purchases will be notified in writing regarding the expected shipping date.</p></li>
            <li><p><strong>Replacement &amp; Returns Policy: </strong>Replacement and return policy can vary for different manufacturers. Equipment, which has been found defective will be returned to the manufacturer for a replacement item. In this case, the shipping costs will be covered by the manufacturer.</p></li>
            <li>
                <p>
                    <strong>Refund Policy:</strong>
                    <br />We refund all cases of fraud and unauthorized transactions included shipping and handling charges. Additionally, refunds can be requested up to 1 week after placing an order. Additional refunds are issued at the discretion of the company.
                    <br />Customers are restricted to receiving a single refund per product ordered. Repetitive refunds are not permitted unless the product, as delivered to you, is defective. We reserve the right to refuse a refund to any customer who repeatedly requests refunds or who, in our judgment, requests refunds in bad faith.
                    <br />In order to process your refund, you must supply us with your name and delivery address. If you provide us with insufficient or incorrect information your refund will be delayed.
                    <br />Once a refund has been approved please allow for up to 10 days for the refund to be applied.
                    <br />Depending on the bank that issues the credit card, your refund can take up to ten (10) days to appear on your credit card statement. If you have any questions about whether a refund has been issued by us, please call Our Customer Service Department.
                </p>
            </li>
                
            <li><p>All goods sold by FFL are produced by our manufacturing partners. They are sold in accordance with the manufacturers and/or standard specifications (if any) applicable to such goods and subject to these Conditions of Sale and no contrary stipulations by the Purchaser shall be valid unless specifically authorized by us in writing.</p></li>
            <li><p>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. In that case, the Purchaser will be informed and fully reimbursed. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors.<br /> You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed.</p></li>
            <li><p>Prices quoted by FFL are ex seller&rsquo;s warehouse unless otherwise agreed in writing. The Purchaser is responsible to effect whatever insurance is required at the Purchaser&rsquo;s expense. Invoices are payable on presentation. Prices are subject to change without notice. In particular, FFL reserves the right to vary quoted prices:<br /> To conform to its price for similar goods at the date of dispatch;<br /> ii. To take account of changes in manufacturers&rsquo; costs or other costs between quotation and delivery.</p></li>
            <li><p>Prices of goods sold by our producers may vary after the Purchaser's order and before the sending of the goods. If the prices increase and FFL cannot take them in charge, the Purchaser shall be informed of this change. If he refuses the new price, FFL will have the right to cancel the order, and the Purchaser will be fully reimbursed.</p></li>
            <li><p>FFL will accept returns of goods incorrectly supplied, provided we are notified within 7 days of receipt of the goods. In the event of FFL accepting return of goods incorrectly ordered, FFL will charge a re-stocking fee of 10%.<br /> CUSTOMERS ARE EXPRESSLY REQUESTED NOT TO RETURN GOODS WITHOUT OBTAINING BOTH AUTHORIZATION TO DO SO AND INSTRUCTIONS ON THE PACKING AND CARRIAGE OF SUCH GOODS.<br /> A return label will be issued and sent to the Purchaser.<br /> Credit for goods returned can only be given, or exchanges made, if written permission has been obtained beforehand and if the returned goods are in the original unopened containers and in sealable condition.<br /> Consumables and perishable products are non-returnable!<br /> In case the Purchaser wishes to cancel an order :<br /> - if the order has not yet been passed on to the Producer, or the Producer can cancel it without supplementary cost, FFL will charge a cancellation fee of 10% the initial price<br /> - if the order has already been passed on to the Producer, and the Producer cannot cancel it anymore, FFL will charge the full price of the order.</p></li>
            <li><p>The purchaser shall give written notice to us about any defect immediately, but within one week on receipt of the delivery or service at the latest. We shall be informed in writing about defects that cannot be discovered even after careful examination within this period of time immediately after detection.</p></li>
            <li><p>Ownership of the goods remains vested in FFL until fully paid for by the Purchaser. Until payment is made the Purchaser shall hold the goods on a fiduciary basis. The Purchaser shall be entitled to sell any Goods in the possession of the Purchaser but owned by FFL and the Purchaser shall be under a fiduciary duty to account to FFL for the proceeds of sale to the extent that any monies are owed by the Purchaser to FFL. The risk of the goods sold shall pass to the Purchaser at the point of delivery to the Purchaser or to the delivery agent. It is the responsibility of the Purchaser to request and pay for the insurance of goods ordered. Until such time as title to the Goods passes to the Purchaser (and provided the Goods are still in existence and have not been resold) FFL shall be entitled at any time to require the Purchaser to deliver up the Goods to FFL and if the Purchaser fails to do so, to enter upon the premises of the Purchaser or any third party where the Goods are stored and repossess the Goods.</p></li>
            <li><p>Claims for goods lost or damaged in transit should immediately be logged with the carrier concerned. FFL will not entertain any claim for non-delivery unless written notification is received by FFL within seven days of receipt.</p></li>
            <li><p>Under no circumstances whatsoever shall FFL responsibility (under contract tort breach of statutory duty or otherwise) to the Purchaser exceed the invoice price of the particular goods being the subject of the claim.</p></li>
            <li><p>FFL shall have no liability whatsoever or howsoever to the Purchaser by way of indemnity or by reason of any breach of the Contract or a statutory duty or by tort (including but not limited to negligence) for any loss of profit, loss of use, loss of production, loss of contracts or for financial or economic loss or for any indirect or consequential damage whatsoever suffered by the purchaser even where such loss and/or damage had been within the contemplation of the parties at the date of entering into the contract. Nothing in this clause shall exclude any liability for fraudulent misrepresentation.</p></li>
            <li><p>Without prejudice to any other remedies available to FFL, if the Purchaser makes a voluntary arrangement with its creditors or becomes subject to an administration order or (being an individual) becomes bankrupt or (being a company) goes into liquidation (other than for the purposes of amalgamation or reconstruction), FFL shall be entitled to cancel any agreement with the Purchaser or suspend any further deliveries and if the goods have been delivered but not paid for the price shall immediately become due and payable notwithstanding any previous arrangement.</p></li>
            <li><p>Delivery dates provided by FFL are indicative only and made without obligation. Delivery dates depend on each good and are independent from one another. Time for delivery shall not be of the essence of the contract unless previously agreed by FFL in writing and in any event failure to deliver goods by any specific date or any late delivery will not provide grounds for cancellation of any order for goods specially obtained for the Purchaser&rsquo;s order.</p></li>
            <li><p>The Purchaser accepts that all goods supplied by FFL are to be used strictly in accordance with the manufacturer&rsquo;s printed package insert supplied with the goods or applicable at time of supply. The Purchaser agrees that any advice or assistance by FFL staff is given in good faith and will not be treated as a recommendation to adopt any procedure contrary to the manufacturer&rsquo;s printed package insert of the catalogue or commonly accepted Good Laboratory Practice.</p></li>
            <li><p>Certain content, products and services available via our Service may include materials from third parties.<br /> Third-party links on this site may direct you to third-party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third-parties.<br /> We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party.</p></li>
            <li><p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order).<br /> We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated.</p></li>
            <li><p>The Purchaser accepts that FFL does not routinely undertake Quality Control testing on goods not of its own manufacture. The Purchaser accepts that responsibility rests solely on the Purchaser to determine that goods and procedures obtained from FFL are suitable for Purchaser&rsquo;s own purposes. The Purchaser agrees to hold FFL harmless and indemnify FFL against claims by all and any third party arising out of the use of the goods whether these claims are the result of direct or consequential damage.</p></li>
            <li><p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p></li>
            <li><p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes.<br /> These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site.<br /> If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p></li>
            <li><p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision.<br /> These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service).<br /> Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p></li>
            <li><p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the USA laws.</p></li>
            <li><p>You can review the most current version of the Terms of Service at any time at this page.<br /> We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes.</p></li>
            <li><p>The Purchaser accepts these Terms and Conditions of Sale and the undersigned is authorized to sign acceptance on behalf of the Purchaser.</p></li>
            <li><p>For the avoidance of doubt nothing in these Terms and Conditions shall confer on any third party any benefit or the right to enforce any term of the contract.</p></li>
            <li><p>Notwithstanding anything to the contrary expressed in or to be implied from these Terms and Conditions, these Terms and Conditions shall be deemed to contain the entire agreement and understanding between the parties which supersedes any and all previous agreements and understandings between the parties and the purchaser acknowledges that in accepting the prices quoted by FFL and entering into these Terms and Conditions the Purchaser has not relied or will not rely on any statements, representations, warranties or undertakings which are not expressly set out in the documents referred to above including without limitation to the generality of the foregoing any undertakings contained in any other documents made available by FFL prior to the execution of these Terms and Conditions. This clause shall not exclude any liability for fraudulent misrepresentation.</p></li>
            <li><p>Please note this website uses cookies to function correctly and to ensure user experience is improved. It also contains certain tracking cookies which allow tracking of movement through the website and pages visited. This again is to improve user experience. However if you are not happy to continue using this website please exit your browser now. We will assume your agreement to the use of these cookies until informed otherwise.</p></li>
        </ol>
        <p><br /> ACCEPTANCE OF TERMS OF USE: By using, visiting, or browsing the Website, as well as placing an order with FlowCell Inc. through the Website, You accept, without limitation or qualification, these Terms of Use and agree, without limitation, to the terms of Our Privacy Statement. By accessing, using or ordering products through the Website, You affirm that You have read this Agreement and understand, agree, and consent to all Terms contained herein.</p>
        <p>&nbsp;</p>
        <p><strong>FlowCell, Inc.<br /> 29 Littles Point Rd<br /> Swampscott, MA 01907 / USA</strong></p>
        <p>&nbsp;</p>
    </div>
  </div>
@endsection
